name: First Workflow GitHub Actions GO

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ main, developer ]
  pull_request:
    branches: [ main, developer ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:	
    name: Runnig the Job test
    runs-on: self-hosted
    steps:
      - name: Step 1 - Keep Going
        uses: actions/checkout@v2

      - name: Step 2 - Run a one-line script
        run: echo Hello, world!

      - name: Step 3 - Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo Hello guys.
